### ISSUE TITLE
add read log query parameters

### ISSUE THREAD

**Issue by Veitor** [allansun/kubernetes-php-client#10]
```php
/**
     * read log of the specified Pod
     *
     * @param $namespace
     * @param $name
     * @return string|mixed
     */
    public function readLog($namespace = 'default', $name)
    {
        return $this->parseResponse(
        	$this->client->request('get',
        		"/api/v1/namespaces/{$namespace}/pods/{$name}/log"
        		,[
        		]
        	)
        	, 'readCoreV1NamespacedPodLog'
        );
    }
```
`Kubernetes\API\Pod` class, need to add query parameter to `readLog` function as third parameter.

there are query parameters in Kubernetes API Reference : https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12

**Comment by stafot** [comment]
I faced the same problem very recently. I needed to pass `container` query param. For a full list of possible params check [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#-strong-misc-operations-pod-v1-core-strong-). My temporary workaround was to extend the `Pod:class`, create a new function and pass the query param I needed. My proposition though is to solve it properly, by using the [guzzle ability to pass query params](http://docs.guzzlephp.org/en/stable/quickstart.html#query-string-parameters).  So an example implementation could be 
```php
/**
     * read log of the specified Pod
     *
     * @param $namespace
     * @param $name
     * @return string|mixed
     */
    public function readLog(string $namespace = 'default',string  $name, array $params =[])
    {
        return $this->parseResponse(
        	$this->client->request('get',
        		"/api/v1/namespaces/{$namespace}/pods/{$name}/log"
        		,[
                            'query' => $params
        		]
        	)
        	, 'readCoreV1NamespacedPodLog'
        );
    } 
```
Dear @allansun, if you are open to contributions let me know to raise a PR that will propose this change.

**Comment by allansun** [comment]
@stafot Thanks for bring this up. PR is welcome!

**Comment by stafot** [comment]
Could you please provide some instructions on how to pull swagger.json after we pull master branch because it is not included. Do you have a manual flow for backward releases? If yes could you describe the steps to find a way to automate it? Thanks in advance, @allansun

**Comment by allansun** [comment]
The master branch is deliberately left blank. Each version was generated
separately (via external CI) and pushed back to GitHub.

Unfortunately I haven't found a better way for backward releases. What I
would do is to generate each version again and attach patch number at the
end of the version number...

I had a look at the swagger file last night and can confirm you are right
there are parameters there, so the generated code SHOULD have additional
parameter to the readLog method, looks like a bug to me, I will look into
it.

**Comment by allansun** [comment]
@stafot @Veitor  Thanks for the long waiting, I have 'almost' fully refactored the code generation logic for API part, all 'parameters' as described in the swagger files are correctly parsed and implemented into the generated code.

Your requested $queries can not be injected into the request

https://github.com/allansun/kubernetes-php-client/blob/56d0a4e5906db1428751d45fd92454864f0b6810/src/API/Pod.php#L512-L523

If you noticed I've also managed to put the accepted parameters as PHPDoc, so you don't always have to go through to the Kubernetes documentation, a validator maybe implemented in future release, but it think at least it works now.

https://github.com/allansun/kubernetes-php-client/blob/56d0a4e5906db1428751d45fd92454864f0b6810/src/API/Pod.php#L478-L513

Please notice I didn't re-tag the releases, instead I `created` a patch to the latest stable release of each major version, you can reference to those specific composer version for the latest generated code. All new code generated from now on will follow the new code template.

![xc060 10-04 20-36-56](https://user-images.githubusercontent.com/20531/95025612-f9b78080-0682-11eb-8415-50c8179b2c94.png)

![7z0eq 10-04 20-49-43](https://user-images.githubusercontent.com/20531/95025641-3a16fe80-0683-11eb-9ed6-80607636a9c4.png)

**Comment by stafot** [comment]
Great @allansun, I will try it tomorrow and let you know. Thanks for addressed this.

**Comment by stafot** [comment]
Worked in my case!
