### ISSUE TITLE
Allow for extension using Custom Objects

### ISSUE THREAD

**Issue by dariusj18** [allansun/kubernetes-php-client#11]
Kubernetes can be extended with custom resource definitions.  It seems relatively easy to create ones own AbstractAPI extensions and Models, however the AbstractAPI's parseResponse() method uses a static class to tie results and objects together. 

This is just a preliminary feature request.  I have not delved too deep in yet, so thre may be things I am not taking into account.

**Comment by allansun** [comment]
Sorry I just ignored your request for 2 years....

I will close this issue for now, if you still need it I will look into implementation.

**Comment by dariusj18** [comment]
It's ok, I ended up being able to do it, it just required a lot of replumbing.  I don't even remember exactly how.
