### ISSUE TITLE
[1.19+] Not able to use Ingress API v1 models.

### ISSUE THREAD

**Issue by leroy** [allansun/kubernetes-php-client#14]
The Ingress API has been available since 1.19 under the v1 api version. However the ingress API class still requires the v1beta1 model version. Is this an error in the swagger spec or something the generation code could account for?

https://github.com/allansun/kubernetes-php-client/blob/ac99b731e63af050318690b14193dcbe9aa685d2/src/API/Ingress.php#L233

**Comment by allansun** [comment]
Hi @leroy sorry about this late reply, I've been away dealing with family affairs.

After looking into the generated code and the K8S swagger file, I think it's neither the fault of the code generator nor the Swagger file.

Even though the Ingress API class requires the v1beta1 model in the header, it also provides methods for the new Networking namespace API endpoint access, with the correct V1 model required.

https://github.com/allansun/kubernetes-php-client/blob/ac99b731e63af050318690b14193dcbe9aa685d2/src/API/Ingress.php#L233-L245

https://github.com/allansun/kubernetes-php-client/blob/ac99b731e63af050318690b14193dcbe9aa685d2/src/API/Ingress.php#L1128-L1140

The reason default `list` method is still pointing v1beta1 endpoint I believe should be for backward compatibility. I am sure when such endpoint is fully deprecated it should be updated to the new Networking endpoint.

If you are eager to use the new Networking API, you can use the method with `NetworkingV1` postfix. Though I think you'd better off still use the default list/ read/ create/ delete methods so you don't have to change your code again when the v1beta1 is deprecated.

**Comment by leroy** [comment]
Hey man, thanks for the response!

I'll look into the NetworkingV1 methods!

Never apologize for responding "late" on something you created for free for others to enjoy. 

Thank you for your time and effort! ✨
