### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\modify_request

### ISSUE THREAD

**Issue by yuchen** [allansun/kubernetes-php-client#15]
Hi, 

code
```php
return $handler(Psr7\modify_request($request, $modify), $options);
```
update into 
```php
return $handler(Psr7\Utils::modifyRequest($request, $modify), $options);
```

:D

**Comment by allansun** [comment]
改好了， 这个代码是在依赖库 https://github.com/allansun/kubernetes-php-runtime 里的，太久以前写的了我还找了一下 😂

你直接在你自己的库里 composer update一下就应该好了。

可以运行 composer show kubernetes/php-runtime 确认一下，里面的 version 是 1.0.9 就对了。

**Comment by yuchen** [comment]
非常感谢~
