### ISSUE TITLE
"Kubernetes\Client" is missing?

### ISSUE THREAD

**Issue by piwi91** [allansun/kubernetes-php-client#3]
I can't find the Client class as mentioned in the README file. It looks like it is missing in the repository.

**Comment by allansun** [comment]
It is in a separate library called '[kubernetes/php-runtime](https://packagist.org/packages/kubernetes/php-runtime)' , if you run `composer install` the lib would automatically download

**Comment by allansun** [comment]
Ha I see what you mean! Yes that's my fault forgetting to update the doc, I changed the project structure to take the core functions out, they are moved to `KubernetesRuntime` namespace now. I will update the README now.

**Comment by allansun** [comment]
@piwi91 Just done it!

**Comment by piwi91** [comment]
Thx, I already found it by inspecting the code ;) Thanks for updating the docs
