### ISSUE TITLE
ConfigMapAPI is not found 

### ISSUE THREAD

**Issue by mohamedalkhiami** [allansun/kubernetes-php-client#4]
hi there 
I'm trying to follow your documentation, I'm facing this error  
Kubernetes\Model\Io\K8s\Api\Core\V1\ConfigMap' not found in

**Comment by allansun** [comment]
Could you post your code? Has the ‘composer install’ done successfully? Which version are you using?

**Comment by allansun** [comment]
Since there's no replies to this issue, I will mark it as closed.
