### ISSUE TITLE
laravel框架中PodExecOptions->connectPostPodExec()如何调用？

### ISSUE THREAD

**Issue by dapeng235** [allansun/kubernetes-php-client#64]
laravel 7版本
如何处理websock请求？

**Comment by allansun** [comment]
我没找到这么个接口啊。。。

**Comment by dapeng235** [comment]
安装后，kubernetes/php-runtime项目下的。namespace Kubernetes\API

**Comment by allansun** [comment]
你能直接给个链接么？ kubernetes/php-runtime 是个很简单的基础库，不应该有涉及到Pod的东西啊

**Comment by dapeng235** [comment]
![image](https://user-images.githubusercontent.com/17588376/203754180-91213926-1cab-4142-ac9c-f9257fe8e0f0.png)
![image](https://user-images.githubusercontent.com/17588376/203754296-0519d1c2-d101-45e4-8459-b4443551a4ce.png)
为了在pod内执行exec，做shell命令执行

**Comment by allansun** [comment]
我查了整个Kubernetes的文档没发现哪个API是用websocket做接口的。。。

你找到的这个接口在swagger里是确实有定义，但是[官网文档](https://v1-21.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#pod-v1-core)上都没描述。。。
![swagger json 2022-11-24 10-16-19](https://user-images.githubusercontent.com/20531/203758485-41e21ad1-b1a4-400d-b916-386ee968c998.png)

我不知道你具体想这么操作的目的是什么，不过我们有类似的需求是通过自己开放一个HTTP的端口然后去请求的。

如果是定期跑的任务你可以用Kubernetes的CronJob机制，或者说直接在Docker里定义一个Linux下的Cronjob去跑。。。

**Comment by dapeng235** [comment]
感谢，我再看看
