### ISSUE TITLE
PortForward Issue

### ISSUE THREAD

**Issue by tarekesmailmatra** [allansun/kubernetes-php-client#9]
this error appear in pod port forward

object(Kubernetes\Model\Io\K8s\Apimachinery\Pkg\Apis\Meta\V1\Status)#47 (10) {
  ["apiVersion"]=>
  string(2) "v1"
  ["code"]=>
  NULL
  ["details"]=>
  NULL
  ["kind"]=>
  string(6) "Status"
  ["message"]=>
  NULL
  ["metadata"]=>
  NULL
  ["reason"]=>
  NULL
  ["status"]=>
  NULL
  ["isRawObject"]=>
  bool(true)
  ["rawData"]=>
  array(7) {
    ["kind"]=>
    string(6) "Status"
    ["apiVersion"]=>
    string(2) "v1"
    ["metadata"]=>
    array(0) {
    }
    ["status"]=>
    string(7) "Failure"
    ["message"]=>
    string(24) "Upgrade request required"
    ["reason"]=>
    string(10) "BadRequest"
    ["code"]=>
    int(400)
  }
}

**Comment by allansun** [comment]
Looks like this is more to do with your Kubernetes setup, nothing to do with the lib it self.

Without further context (client/server version, actual payload you sent) I cannot diagnose more, but I suggest you try to google the actual error message "Upgrade request required"
